services:
  
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    ports:
      - "5435:5432" 
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: user_service
    volumes:
      - /containers-data/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d user_service"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - /containers-data/redis-data:/data
 
  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx256m
    volumes:
      - ./discovery-service/build/libs/app.jar:/app/app.jar

  
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx256m
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    volumes:
      - ./api-gateway/build/libs/app.jar:/app/app.jar
  
  auth-service:
    build: ./auth-service
    container_name: auth-service
    
    
    depends_on:
      discovery-service:
        condition: service_started
      postgres-db:
        condition: service_healthy
      kafka:
        condition: service_healthy 
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx512m
      
      - SERVER_PORT=8081
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/user_service
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    volumes:
      - ./auth-service/build/libs/app.jar:/app/app.jar

  user-service:
    build: ./user-service
    container_name: user-service
    
    depends_on:
      discovery-service:
        condition: service_started
      postgres-db:
        condition: service_healthy
      kafka:
        condition: service_healthy 

    environment:
      - JAVA_TOOL_OPTIONS=-Xmx512m
      
      - SERVER_PORT=8082
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/user_service
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=root
      #- SPRING_JPA_HIBERNATE_DDL_AUTO=update
      #- SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    volumes:
      - ./user-service/build/libs/app.jar:/app/app.jar
  message-service:
    build: ./message-service
    container_name: message-service
    
    depends_on:
      discovery-service:
        condition: service_started
      postgres-db:
        condition: service_healthy
      kafka:
        condition: service_healthy 

    environment:
      - JAVA_TOOL_OPTIONS=-Xmx512m
      
      - SERVER_PORT=8082
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/user_service
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=root
      #- SPRING_JPA_HIBERNATE_DDL_AUTO=update
      #- SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    volumes:
      - ./message-service/build/libs/app.jar:/app/app.jar

  chat-service:
    build: ./chat-service
    container_name: chat-service
    
    depends_on:
      discovery-service:
        condition: service_started
      postgres-db:
        condition: service_healthy

    environment:
      - JAVA_TOOL_OPTIONS=-Xmx512m
      
      - SERVER_PORT=8083
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/user_service
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_SHOW_SQL=true
    volumes:
      - ./chat-service/build/libs/app.jar:/app/app.jar
  kafka:
    image: bitnamilegacy/kafka:latest
    container_name: kafka
    ports:
      - "9094:9094"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions.sh --bootstrap-server localhost:9092 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8090:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight-ui
    restart: always
    user: root
    ports:
      - "5540:5540"
    volumes:
      - /containers-data/redis-data:/data
    depends_on:
      - redis

  rabbitmq:
    image: rabbitmq:3-management
    container_name: my-rabbitmq
    restart: always
    user: root
    ports:
      
      - "15672:15672" 
      
      - "61613:61613" 
      
      - "5672:5672"   
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    
    command: >
      bash -c "rabbitmq-plugins enable --offline rabbitmq_stomp && 
      rabbitmq-server"
    volumes:
      
      - /containers-data/rabbit-data:/var/lib/rabbitmq